TCPConnection:
  remote_server_address: 192.168.0.24
  remote_server_port: 23506
  receive_address: 192.168.0.25
  receive_port: 23507
  buffer_size: 2048
  socket_timeout: 3.0

Database:
  path: 'Resources/Database/objects.db'
  create_schema_sql: 'Resources/Database/CreateSchema.sql'
  insert_to_symbol: 'Resources/Database/InsertToSymbol.sql'
  insert_to_simple_object: 'Resources/Database/InsertToSimpleObject.sql'
  insert_to_combined_object: 'Resources/Database/InsertToCombinedObject.sql'

Camera:
  default_frame_rate: 60

Logger:
  console_print: True
  file_print: True
  logs_path: 'Logs/'
