CREATE TABLE COMBINE_OBJECT
(
  ID INTEGER PRIMARY KEY,
  SHAPE INTEGER,
  WIDTH INTEGER,
  HEIGHT INTEGER,
  TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SIMPLE_OBJECT
(
  ID INTEGER PRIMARY KEY,
  SHAPE INTEGER NOT NULL,
  WIDTH INTEGER NOT NULL,
  HEIGHT INTEGER NOT NULL,
  COLOR INTEGER NOT NULL,
  PATTERN INTEGER NOT NULL,
  PATTERN_COLOR INTEGER NOT NULL,
  PARENTCOMBINEDOBJECT INTEGER,
  TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PARENTCOMBINEDOBJECT) REFERENCES COMBINE_OBJECT(ID)
);

CREATE TABLE SYMBOL
(
  ID INTEGER PRIMARY KEY,
  SHAPE INTEGER NOT NULL,
  WIDTH INTEGER NOT NULL,
  HEIGHT INTEGER NOT NULL,
  COLOR INTEGER NOT NULL,
  PARENTSIMPLEOBJECT INTEGER NOT NULL,
  TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PARENTSIMPLEOBJECT) REFERENCES SIMPLE_OBJECT(ID)
);

