TCPConnection:
  agent_address: 127.0.0.1
  agent_port: 23507
  receive_address: 127.0.0.1
  receive_port: 23506
  buffer_size: 2048
  socket_timeout: 3.0

Logger:
  console_print: True
  file_print: True
  logs_path: 'Logs\'