TCPConnection:
  agent_address: 192.168.0.25
  agent_port: 23507
  buffer_size: 2048
  receive_address: 192.168.0.24
  receive_port: 23506
  socket_timeout: 3.0

Logger:
  console_print: True
  file_print: False
  logs_path: 'Logs\'
